Sprint 15 v.1 add-item-request
Alexander-Kuzin/java-shareit pull request #3
Opened 2023-08-14 07:08 UTC by Alexander-Kuzin

2023-08-14 15:13 UTC, Frilock requested changes
В целом здорово, ряд мелких комментариев и можно принимать

2023-08-14 15:13 UTC, Frilock commented on pom.xml
> +			<version>3.8.1</version>
Вообще версии библиотек лучше указывать в properties, чтобы сразу привыкать к такой практике.

2023-08-14 15:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingStorage.java
> +    List<Booking> findAllByBookerAndCurrent(@Param("user") User booker,
Вообще в тех методах где вы работаете с объектом pageable, лучше возвращать не просто лист, а объект Page. На мой взгляд, такой код будет более понятным.

2023-08-14 15:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          if (!items.isEmpty() && items.get(0).getOwner().getId() == userId) {
Можно заменить на тернарное выражение - будет компактнее

2023-08-14 15:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Set<Comment> comments;
Еще можно инициализировать коллекции прям тут, чтобы не проверять везде на null

2023-08-14 15:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/mappers/ItemRequestMapper.java
> +
Лишняя пустая строка

2023-08-14 15:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private String description;
Вообще вот те размеры которые вы указываете в скриптах генерации таблиц, также лучше указывать в аннотации Column, чтобы в случае чего не лазить в БД и не смотреть размерность

2023-08-20 10:49 UTC, Frilock approved these changes
Принято, по договоренности, жду изменений в следующем ПР.

2023-08-20 17:41 UTC, Alexander-Kuzin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private String description;
Действительно, должно быть удобно! 
Спасибо, поправил

2023-08-20 17:41 UTC, Alexander-Kuzin commented on src/main/java/ru/practicum/shareit/mappers/ItemRequestMapper.java
> +
Спасибо, убрал

2023-08-20 17:42 UTC, Alexander-Kuzin commented on pom.xml
> +			<version>3.8.1</version>
Так и делал раньше, забыл причесать при копи-пасте. 
Поправил, спасибо!

2023-08-20 17:48 UTC, Alexander-Kuzin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Set<Comment> comments;
Добавил инициализацию

2023-08-20 18:55 UTC, Alexander-Kuzin commented on src/main/java/ru/practicum/shareit/booking/BookingStorage.java
> +    List<Booking> findAllByBookerAndCurrent(@Param("user") User booker,
Спасибо, отрефакторил

2023-08-20 18:55 UTC, merged