Sprint 16 v.1 add-docker
Alexander-Kuzin/java-shareit pull request #4
Opened 2023-08-20 21:33 UTC by Alexander-Kuzin

2023-08-21 08:53 UTC, Frilock requested changes
Добрый день, все здорово, 1 просьба - не удаляйте тесты на валидацию, а перенесите их в gateway

2023-08-21 08:53 UTC, Frilock commented on server/pom.xml
> +<!--        <dependency>-->
Нужно убрать закоментированный код

2023-08-21 08:53 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/GatewayBookingController.java
> +        return
в 1 строчку вроде нормально влезает)

2023-08-21 08:53 UTC, Frilock commented on server/src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> -    void getExceptionWithCreateWithoutHeader() throws Exception {
Тесты на валидацию не удаляйте, а перенесите в  gateway

2023-08-21 16:31 UTC, Alexander-Kuzin commented on gateway/src/main/java/ru/practicum/shareit/booking/GatewayBookingController.java
> +        return
У меня нет разумного объяснения тому, как так получилось =) 
Поправил, спасибо!

2023-08-21 16:32 UTC, Alexander-Kuzin commented on server/pom.xml
> +<!--        <dependency>-->
Поправил, спасибо

2023-08-23 13:00 UTC, Frilock requested changes
Сборка не проходит

2023-08-23 13:57 UTC, Frilock approved these changes
Принято

2023-08-23 16:10 UTC, merged